#### A Simple Classification Example: Using 8x8 handwritten digit images for c

In [1]:
from sklearn import datasets

digits = datasets.load_digits()

In [2]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
digits.target


array([0, 1, 2, ..., 8, 9, 8])

In [4]:
digits.data.shape

# It looks like the digit images are 8x8 images and there are 1797 images in the dataset.


(1797, 64)

In [5]:
digits.data[0]
    

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [6]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [7]:
digits.target.shape

(1797,)

In [9]:
digits.target.reshape(1797,1)
digits.target.shape

(1797,)

Well ,we loaded the built in datasets like **digits** , But how to load extenal datasets, see the article from sklearn docs by clicking [here](http://scikit-learn.org/stable/datasets/index.html#external-datasets)

In [ ]:
# importing an SVM classifier and instantiating with few important parameters.
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

We call our estimator instance *clf,* as it is a classifier. It now must be fitted to the model, that is, it must learn from the model. This is done by passing our training set to the **fit** method. As a training set, let us use all the images of our dataset apart from the last one. We select this training set with the [:-1] Python syntax, which produces a new array that contains all but the last entry of digits.data:

In [ ]:
clf.fit(digits.data[:-1], digits.target[:-1])


Now you can predict new values, in particular, we can ask to the classifier what is the digit of our last image in the digits dataset, which we have not used to train the classifier:

In [ ]:
clf.predict(digits.data[-1:])

the predicted digit is **8** ,and the actual target label is ,let us check


In [ ]:
print("the actual last digit is: {}" .format(digits.target[-1:]))